name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -v
    - run: make

  build-linux-meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install meson ninja
    - run: gcc -v
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson compile -C builddir/

  build-macos-meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install meson ninja
    - run: clang -v
    - run: meson setup builddir/
      env:
        CC: clang
    - run: meson compile -C builddir/

  build-msvc-meson:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install meson ninja
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64
    - run: meson setup builddir
    - run: meson compile -C builddir

  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: clang -v
    - run: make CC="clang --target=wasm32"
    - uses: actions/upload-artifact@v4
      with:
        name: liblc3.wasm
        path: bin/liblc3.wasm

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-wasm
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    - run: rm web/liblc3.wasm
    - uses: actions/download-artifact@v4
      with:
        name: liblc3.wasm
        path: web
    - uses: actions/upload-pages-artifact@v3
      with:
        path: web
    - uses: actions/deploy-pages@v4

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install scipy numpy
    - run: gcc -v
    - run: make test

  install-python-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install .
