name: Release

on:
  release:
    types: [published]

jobs:
  upload-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: make CC="clang --target=wasm32"
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: bin/liblc3.wasm
        asset_name: liblc3.wasm
        asset_content_type: application/wasm
