name: Release

on:
  release:
    types: [published]

jobs:
  upload-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: liblc3.wasm
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: liblc3.wasm
        asset_name: liblc3.wasm
        asset_content_type: application/wasm
